# Generated by Django 4.0 on 2022-03-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='论坛编号')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='论坛名称')),
                ('forumIcon', models.ImageField(upload_to='forumIcon', verbose_name='论坛头像')),
                ('intro', models.TextField(default='', verbose_name='简介')),
                ('tag', models.CharField(max_length=32, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者')),
            ],
            options={
                'db_table': 'forum_forum',
            },
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='帖子编号')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创贴时间')),
                ('tag', models.CharField(max_length=32, verbose_name='帖子分类')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建者')),
                ('pubForum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='创建论坛')),
            ],
            options={
                'db_table': 'forum_topic',
            },
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('m_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='论坛')),
                ('m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='论坛成员')),
            ],
            options={
                'db_table': 'forum_user',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('puber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='评论人')),
                ('topicComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topic', verbose_name='评论对象')),
            ],
            options={
                'db_table': 'forum_comment',
            },
        ),
    ]
