# Generated by Django 4.0 on 2022-04-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tag',
            field=models.CharField(max_length=32, null=True, verbose_name='帖子分类'),
        ),
    ]
