# Generated by Django 4.0 on 2022-04-11 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_topic_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='评论内容'),
            preserve_default=False,
        ),
    ]
