# Generated by Django 4.0 on 2022-03-11 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='聊天信息编号')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('postTime', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('messageForum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='发布论坛')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='消息接收人', to='user.user', verbose_name='消息接收人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='消息发送人', to='user.user', verbose_name='消息发送人')),
            ],
            options={
                'db_table': 'chat_chatMessage',
            },
        ),
    ]
