# Generated by Django 4.0 on 2022-04-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_userclass_delete_userclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
