# Generated by Django 4.0 on 2022-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userIcon',
            field=models.TextField(verbose_name='用户头像'),
        ),
    ]
