# Generated by Django 4.0 on 2022-03-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pub_notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='通知编号')),
                ('title', models.CharField(max_length=32, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='发送范围')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='通知发送人', to='user.user', verbose_name='通知发布人')),
            ],
            options={
                'db_table': 'notify_pub_notice',
            },
        ),
        migrations.CreateModel(
            name='notice_receive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.pub_notice', verbose_name='通知编号')),
                ('reveiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='接收人')),
            ],
            options={
                'db_table': 'notify_notice_receive',
            },
        ),
    ]
