# Generated by Django 4.0 on 2022-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
