# Generated by Django 4.0 on 2022-04-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice_receive',
            old_name='reveiver',
            new_name='receiver',
        ),
    ]
